name: popperscuventas
description: Aplicación Flutter para ventas, inventario, clientes y reportes CSV.
publish_to: 'none' # No publicar en pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  path_provider: ^2.1.5
  path: ^1.9.0
  intl: ^0.19.0
  csv: ^6.0.0

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.1
  csv: ^6.0.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  file_picker: ^8.0.0
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
