name: popperscuventas
description: Aplicación Flutter para registro de ventas, inventario y reportes
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # Base de datos local
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.5

  # Compartir y exportar
  share_plus: ^7.2.2
  cross_file: ^0.3.4

  # Íconos iOS y Material
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # Activa esta sección si usas imágenes o archivos en assets
  # assets:
  #   - assets/
