name: popperscuv2
description: Ventas e inventario con SQLite y exportación CSV
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: 2.3.3+1
  path_provider: 2.1.5
  intl: 0.19.0
  share_plus: 7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
