name: popperscuventas
description: Aplicación Flutter para ventas, inventario, clientes y reportes CSV.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Datos y almacenamiento
  sqflite: ^2.3.3+1
  path_provider: ^2.1.5
  path: ^1.9.0
  shared_preferences: ^2.2.2

  # Utilidades y formatos
  intl: ^0.19.0
  csv: ^6.0.0
  file_picker: ^8.0.0

  # Compartir/abrir y enlaces
  share_plus: ^7.2.2
  open_filex: ^4.4.0
  url_launcher: ^6.3.0

  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
