name: popperscuv2
description: Base app inventario/ventas/clientes (offline) sin impuestos ni nube.
publish_to: "none"
version: 0.2.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: any
  path_provider: any
  intl: any
  csv: any
  flutter_riverpod: any
  uuid: any
  file_picker: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
