name: ventaspopperscu
description: App de ventas con inventario, historial y reportes en CSV
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  path_provider: ^2.1.3
  csv: ^6.0.0
  dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  path: ^1.9.0
  share_plus: ^7.2.2
  cross_file: ^0.3.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
