name: Android Debug APK (Auto-detect app dir)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**/*.dart'
      - 'pubspec.yaml'
      - 'shell_app/**'
      - '.github/workflows/android-debug.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Detect Flutter app directory
        id: detect_dir
        shell: bash
        run: |
          set -e
          APP_DIR="."
          if [ -f "shell_app/pubspec.yaml" ]; then
            APP_DIR="shell_app"
          elif [ -f "app/pubspec.yaml" ]; then
            APP_DIR="app"
          elif [ -f "mobile/pubspec.yaml" ]; then
            APP_DIR="mobile"
          elif [ -f "client/pubspec.yaml" ]; then
            APP_DIR="client"
          elif [ -f "pubspec.yaml" ]; then
            APP_DIR="."
          else
            echo "❌ No se encontró pubspec.yaml"; exit 1
          fi
          echo "APP_DIR=$APP_DIR" >> $GITHUB_ENV
          echo "Detected APP_DIR=$APP_DIR"

      - name: Regenerate Android project (Flutter 3.27+)
        shell: bash
        run: |
          set -e
          cd "$APP_DIR"
          rm -rf android
          flutter create --platforms=android .

      - name: Flutter pub get
        shell: bash
        run: |
          cd "$APP_DIR"
          flutter pub get

      - name: Build debug APK
        shell: bash
        run: |
          cd "$APP_DIR"
          flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: ${{ env.APP_DIR }}/build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: error
