name: Android Debug APK (Auto)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**/*.dart'
      - 'pubspec.yaml'
      - '.github/workflows/android-debug.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Detect Flutter app directory
        id: detect_dir
        shell: bash
        run: |
          set -e
          APP_DIR="."
          for d in "." "shell_app" "app" "mobile" "client"; do
            if [ -f "$d/pubspec.yaml" ]; then APP_DIR="$d"; break; fi
          done
          echo "APP_DIR=$APP_DIR" >> $GITHUB_ENV
          echo "Detected APP_DIR=$APP_DIR"

      - name: Regenerate Android project (Flutter 3.27+)
        shell: bash
        run: |
          set -e
          cd "$APP_DIR"
          rm -rf android
          flutter create --platforms=android .

      - name: Inject NDK 27 into build.gradle.kts
        shell: bash
        run: |
          set -e
          APP_GRADLE_KTS="$APP_DIR/android/app/build.gradle.kts"
          if [ -f "$APP_GRADLE_KTS" ]; then
            if ! grep -q 'ndkVersion' "$APP_GRADLE_KTS"; then
              awk 'BEGIN{inblock=0} /android \{/ {print; print "    ndkVersion = \"27.0.12077973\""; next} {print}' "$APP_GRADLE_KTS" > "$APP_GRADLE_KTS.tmp" && mv "$APP_GRADLE_KTS.tmp" "$APP_GRADLE_KTS"
              echo "Injected ndkVersion 27.0.12077973"
            else
              echo "ndkVersion already present"
            fi
          else
            echo "WARNING: $APP_GRADLE_KTS not found"
          fi

      - name: Flutter pub get
        shell: bash
        run: |
          cd "$APP_DIR"
          flutter pub get

      - name: Build debug APK
        shell: bash
        run: |
          cd "$APP_DIR"
          flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: ${{ env.APP_DIR }}/build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: error
